package Task1_4;

import java.util.Arrays;

public class Main {
	public static void main(String[] args) {
		Product p1 = new Product("01", "snack", 5000, "fastfood");
		Product p2 = new Product("02", "snack", 5000, "fastfood");
		Product p3 = new Product("03", "banana", 4000, "fruit");
		Product p4 = new Product("04", "orange", 7000, "fruit");
		OrderItem o1 = new OrderItem(p1, 4);
		OrderItem o2 = new OrderItem(p2, 3);
		OrderItem o3 = new OrderItem(p3, 5);
		OrderItem o4 = new OrderItem(p4, 7);
		OrderItem list1[] = { o1, o2, o3, o4 };
		Order listOrder1 = new Order(list1);
		System.out.println(Arrays.toString(listOrder1.getItems()));
		listOrder1.bubbleSort();
		System.out.println("BUBBLE SORT: ");
		System.out.println(Arrays.toString(listOrder1.getItems()));
		System.out.println("===============================================================");
		Product pp1 = new Product("01", "snack", 1000, "fastfood");
		Product pp2 = new Product("02", "snack", 6000, "fastfood");
		Product pp3 = new Product("03", "banana", 4000, "fruit");
		Product pp4 = new Product("04", "orange", 8000, "fruit");
		OrderItem oo1 = new OrderItem(pp1, 4);
		OrderItem oo2 = new OrderItem(pp2, 3);
		OrderItem oo3 = new OrderItem(pp3, 5);
		OrderItem oo4 = new OrderItem(pp4, 7);
		OrderItem list2[] = { oo1, oo2, oo3, oo4 };
		Order listOrder2 = new Order(list2);
		System.out.println(Arrays.toString(listOrder2.getItems()));
		listOrder2.selectionSort();
		System.out.println("SELECTIONSORT : ");
		System.out.println(Arrays.toString(listOrder2.getItems()));
		System.out.println("===============================================================");
		Product ppp1 = new Product("01", "snack", 4000, "fastfood");
		Product ppp2 = new Product("02", "snack", 6000, "fastfood");
		Product ppp3 = new Product("03", "banana", 12000, "fruit");
		Product ppp4 = new Product("04", "orange", 20000, "fruit");
		OrderItem ooo1 = new OrderItem(ppp1, 4);
		OrderItem ooo2 = new OrderItem(ppp2, 3);
		OrderItem ooo3 = new OrderItem(ppp3, 5);
		OrderItem ooo4 = new OrderItem(ppp4, 7);
		OrderItem list3[] = { ooo1, ooo2, ooo3, ooo4 };
		Order listOrder3 = new Order(list3);
		System.out.println(Arrays.toString(listOrder3.getItems()));
		listOrder3.insertionSort();
		System.out.println("INSERTIONSORT : ");
		System.out.println(Arrays.toString(listOrder3.getItems()));
		System.out.println("===============================================================");
		Product pppp1 = new Product("01", "KHOAI TAY", 20000, "fastfood");
		Product pppp2 = new Product("02", "snack", 6000, "fastfood");
		Product pppp3 = new Product("03", "banana", 12000, "fruit");
		Product pppp4 = new Product("04", "orange", 7000, "fruit");
		OrderItem oooo1 = new OrderItem(pppp1, 4);
		OrderItem oooo2 = new OrderItem(pppp2, 3);
		OrderItem oooo3 = new OrderItem(pppp3, 5);
		OrderItem oooo4 = new OrderItem(pppp4, 7);
		OrderItem list4[] = { oooo1, oooo2, oooo3, oooo4 };
		Order listOrder4 = new Order(list4);
		System.out.println(Arrays.toString(listOrder4.getItems()));
		listOrder4.MergeSort();
		System.out.println("MERGESORT : ");
		System.out.println(Arrays.toString(listOrder4.getItems()));
		System.out.println("===============================================================");
		Product ppppp1 = new Product("01", "KHOAI TAY", 20000, "fastfood");
		Product ppppp2 = new Product("02", "xuc xich", 17000, "fastfood");
		Product ppppp3 = new Product("03", "tao", 10000, "fruit");
		Product ppppp4 = new Product("04", "kiwi", 25000, "fruit");
		OrderItem ooooo1 = new OrderItem(ppppp1, 4);
		OrderItem ooooo2 = new OrderItem(ppppp2, 3);
		OrderItem ooooo3 = new OrderItem(ppppp3, 5);
		OrderItem ooooo4 = new OrderItem(ppppp4, 7);
		OrderItem list5[] = { ooooo1, ooooo2, ooooo3, ooooo4 };
		Order listOrder5 = new Order(list5);
		System.out.println(Arrays.toString(listOrder5.getItems()));
		listOrder5.MergeSort();
		System.out.println("QUICKSORT : ");
		System.out.println(Arrays.toString(listOrder5.getItems()));
	}
}
